// examples/react/src/rspc.tsx
import { createClient, FetchTransport } from "@rspc/client";
import { createReactQueryHooks } from "@rspc/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactElement } from "react";
import { createReactQueryHooksProxy } from "@rspc-proxy/react"

import type { Procedures } from "../../bindings";

const client = createClient<Procedures>({
  transport: new FetchTransport("http://localhost:8071/rspc"),
});

const hooks = createReactQueryHooks<Procedures>();
export const rspc = createReactQueryHooksProxy(hooks);

export const queryClient = new QueryClient();

export const RspcProvider = (props: { children: ReactElement }) =>
  <QueryClientProvider client={queryClient} contextSharing={true}>
    <hooks.Provider client={client} queryClient={queryClient}
      children={props.children}
    />
  </QueryClientProvider>

// example/solid/src/rspc.tsx
import { createClient, FetchTransport } from "@rspc/client";
import { createSolidQueryHooks } from "@rspc/solid";
import { createSolidQueryHooksProxy } from "@rspc-proxy/solid";
import { QueryClient } from "@tanstack/solid-query";
import { Procedures } from "../../bindings";
import { FlowProps } from "solid-js";


const hooks = createSolidQueryHooks<Procedures>();
const client = createClient<Procedures>({
  transport: new FetchTransport("http://localhost:8071/rspc"),
});


export const queryClient = new QueryClient();
export const rspc = createSolidQueryHooksProxy<Procedures>(hooks);

export const RspcProvider = (props: FlowProps<{}>) => <hooks.Provider
  client={client}
  queryClient={queryClient}
  children={props.children}
/>
