// examples/solid/src/components/Counter.tsx
import { Match, Switch } from "solid-js";
import { CounterData } from "./Counter.data";

export default function Counter() {
  const { get, set } = CounterData();

  return (
    <div style="margin-top: 10px;">
      <Switch>
        <Match when={get.isError}>
          <p textContent={get.error?.message} class="error-msg" />
        </Match>
      </Switch>

      <div style="display: flex; align-items: center; gap: 4px;">
        <button textContent="-" onClick={() => set.mutate("Dec")} />
        <output textContent={get.data ?? 0} />
        <button textContent="+" onClick={() => set.mutate("Inc")} />
      </div>
    </div>
  );
}

// examples/react/src/components/Counter.tsx
import { CounterData } from "./Counter.data";

export default function Counter() {
  const { get, set } = CounterData();

  return (
    <div style={{ "marginTop": "10px" }}>
      {get.isError &&
        <p>{get.error?.message}</p>
      }
      <div style={{ display: "flex", "alignItems": "center", "gap": "4px" }}>
        <button children="-" onClick={() => set.mutate("Dec")} />
        <output children={get.data ?? 0} />
        <button children="+" onClick={() => set.mutate("Inc")} />
      </div>
    </div>
  );
}
